
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 13:26:38 COT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTA = 4;
  public static final int FINLINEA = 2;
  public static final int error = 1;
  public static final int SUMA = 3;
  public static final int IMPRIMIR = 5;
  public static final int EOF = 0;
  public static final int ENTERO = 6;
}

